"""
title : 0002_even_fibonacci_numbers.py
create : @tarickali 23/03/24
update : @tarickali 23/03/24

Problem Description:
--------------------
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
"""


def solution() -> int:
    N = 4000000
    total = 0
    a, b = 0, 1
    while a + b < N:
        c = a + b
        if c % 2 == 0:
            total += c
        a, b = b, c
    return total


if __name__ == "__main__":
    sol = solution()
    print(sol)
